md_header = '''<!---
This file is automatically generated by the Doxydown scripts.
Do not edit this file as it will be overwritten the next time
the scripts are run.
-->
'''


admonition_template = '''!!! {type} "{name}"
{body}
'''


func_parameters_template = '''### Parameters
{parameters}
'''


func_parameter_template = '''`{name}` - {desc}'''


func_return_template = '''### Returns
{returns}
'''


func_errors_template = '''### Errors<super>[&dagger;](/errors/)</super>
{errors}
'''


func_error_template = '''`{name}` - {desc}'''


func_exceptions_template = '''### Throws
{exceptions}
'''


func_exception_template = '''`{name}` - {desc}'''


c_func_template = '''## {function_name}

```c
{return_type}
{function_name}({argstring});
```

{description}
'''


java_func_template = '''## {function_name}

```java
{visibility} {return_type}
{function_name}({argstring})
{throws}
```

{description}
'''


objc_method_template = '''## {function_name}

```objc
{method_type} ({return_type}){base_name}{argstring};
```

{description}
'''


js_func_template = '''## {function_name}

```js
{function_name}({argstring})
```

{description}
'''


c_struct_template = '''## struct {class_name}

```c
struct {class_name} {{
{struct_body}
}};
```

{description}
'''


c_typedef_struct_template = '''## {class_name}

```c
typedef struct {{
{struct_body}
}} {class_name};
```

{description}
'''


c_struct_member_template = '''{indent}{type} {name};'''


c_struct_member_desc_template = '''### {name}
{description}
'''


c_opaque_typedef_struct_template = '''## {class_name}

```c
struct {class_name};
typedef struct {class_name} {class_name};
```

{description}
'''


c_enum_template = '''## {enum_name}

```c
typedef enum {{
{enum_body}
}} {enum_name};
```

{description}
'''


c_enum_value_template = '''{indent}{value_name}{initializer}'''


c_enum_value_desc_template = '''### {name}
{description}
'''


c_typedef_template = '''## {name}

```c
typedef {type} {name};
```

{description}
'''


java_class_template = '''## {class_name}

```java
{class_declaration} {{
{class_body}
}}
```

{description}
'''


java_class_member_template = '''{indent}{type} {name};'''


java_class_member_desc_template = '''### {name}
{description}
'''


java_class_method_template = '''{indent}{type} {name}({args}){throws};'''


objc_interface_template = '''## {class_name}

```objc
@interface {class_name} : {base_name}
{interface_body}
@end
```

{description}
'''


objc_interface_property_template = '''@property {type} {name};'''


objc_interface_property_desc_template = '''### {name}
{description}
'''


objc_interface_method_template = '''{method_type} ({return_type}){base_name}{args};'''


js_object_template = '''## {object_name}

{description}
'''


js_object_property_desc_template = '''### {name}

{description}
'''


js_object_method_desc_template = '''### {name}()

{description}
'''
